version: 2

project_name: warden

builds:
  - main: .
    binary: warden
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

dockers_v2:
  - images:
      - "ghcr.io/stephnangue/warden"
    tags:
      - "v{{ .Version }}"
      - latest
    dockerfile: Dockerfile.goreleaser

release:
  github:
    owner: stephnangue
    name: warden
  draft: false
  prerelease: auto
  name_template: "Warden v{{ .Version }}"
