{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "warden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "warden.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      {{- include "warden.selectorLabels" . | nindent 6 }}
{{- end }}
