apiVersion: v1
kind: Service
metadata:
  name: {{ include "warden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "warden.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
  # Readiness probe gates sealed/uninit pods out of this Service.
  selector:
    {{- include "warden.selectorLabels" . | nindent 4 }}
