package dev

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stephnangue/warden/internal/playground"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The getting started page renders the tour from these files, one per client.
// They are generated, never edited: a golden file is the only way the page
// can follow a scenario that changes, since the site is built without Go.
// Regenerate them with: go test ./cmd/dev -run TestTourDocs -update
var updateTourDocs = flag.Bool("update", false, "rewrite the docs' tour fragments")

const tourDocsDir = "../../site/src/fragments/tour"

const tourDocsHeader = "<!-- Generated by go test ./cmd/dev -run TestTourDocs -update. Do not edit. -->\n\n"

func renderTourMarkdownAs(name string) string {
	var buf bytes.Buffer
	buf.WriteString(tourDocsHeader)
	renderTourMarkdown(&buf, playground.SetupCommands, playground.Scenarios(), clients[name])
	return buf.String()
}

func TestTourDocsUpToDate(t *testing.T) {
	for _, name := range clientNames() {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(tourDocsDir, name+".md")
			got := renderTourMarkdownAs(name)
			if *updateTourDocs {
				require.NoError(t, os.MkdirAll(tourDocsDir, 0o755))
				require.NoError(t, os.WriteFile(path, []byte(got), 0o644))
				return
			}
			want, err := os.ReadFile(path)
			require.NoError(t, err, "run: go test ./cmd/dev -run TestTourDocs -update")
			assert.Equal(t, string(want), got, "the tour changed; run: go test ./cmd/dev -run TestTourDocs -update")
		})
	}
}

var codeBlock = regexp.MustCompile("(?s)```bash\n(.*?)```\n")

// The page and the CLI give the same commands, in the same groups and order:
// every block after the setup is one renderTour prints for the same address.
func TestTourDocsAgreeWithTheCLI(t *testing.T) {
	for _, name := range clientNames() {
		t.Run(name, func(t *testing.T) {
			md := renderTourMarkdownAs(name)
			text := renderTourAs(name, 0)
			text = strings.ReplaceAll(text, "http://127.0.0.1:8400", docsWardenAddr)
			blocks := codeBlock.FindAllStringSubmatch(md, -1)
			require.Greater(t, len(blocks), 1)
			at := 0
			for _, b := range blocks[1:] {
				i := strings.Index(text[at:], b[1])
				require.NotEqual(t, -1, i, "the CLI prints this block, in this order:\n%s", b[1])
				at += i + len(b[1])
			}
		})
	}
}

// What the page is for: it never asks the reader to run the tour command, and
// its prose survives Markdown.
func TestTourDocs_Markdown(t *testing.T) {
	for _, name := range clientNames() {
		md := renderTourMarkdownAs(name)
		assert.NotContains(t, md, "dev scenarios", name)
		prose := codeBlock.ReplaceAllString(md, "")
		assert.NotContains(t, prose, "\n#", "%s: no headings, which would collide across the page's tabs", name)
		assert.NotContains(t, md, ":::", "%s: Starlight asides do not render in an imported fragment", name)
		assert.Contains(t, md, "List the open issues in &lt;owner&gt;/&lt;repo&gt;.", name)
		assert.NotContains(t, md, "WARDEN_TOKEN", "%s: the page sets the root token, never to a value an agent could guess", name)
		for _, line := range strings.Split(md, "\n") {
			if strings.TrimSpace(line) == "EOF" {
				assert.Equal(t, "EOF", line, "%s: an indented delimiter never ends the heredoc", name)
			}
		}
	}
	assert.Equal(t, "`a < b` &lt;x&gt; &amp;", mdText("`a < b` <x> &"))
}
